"""Add pdf related fields

Revision ID: cad04a32a0ba
Revises: g2h3i4j5k6l7
Create Date: 2025-12-04 13:15:06.466209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cad04a32a0ba'
down_revision: Union[str, Sequence[str], None] = 'g2h3i4j5k6l7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_blocked_companies_user_company'), 'blocked_companies', type_='unique')
    op.drop_constraint(op.f('uq_saved_jobs_user_job'), 'saved_jobs', type_='unique')
    op.add_column('tailored_resumes', sa.Column('pdf_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tailored_resumes', 'pdf_path')
    op.create_unique_constraint(op.f('uq_saved_jobs_user_job'), 'saved_jobs', ['user_id', 'job_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_blocked_companies_user_company'), 'blocked_companies', ['user_id', 'company_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
